---
- hosts: localhost
  become: yes
  roles:
    - { role: base, tags: ['base'] }
    - { role: gnupg, tags: ['gnupg'] }
    - { role: cron, tags: ['cron'] }
    - { role: microcode, tags: ['microcode'], when: "'GenuineIntel' in ansible_processor" }
    - { role: ssh, tags: ['ssh'] }
    - { role: fonts, tags: ['fonts'] }
    - { role: x, tags: ['x'] }
    - { role: sddm, tags: ['sddm'] }
    - { role: i3, tags: ['i3'] }
    - { role: nettools, tags: ['nettools'] }
    - { role: editors, tags: ['editors'] }
    - { role: filesystems, tags: ['filesystems'] }
    - { role: archive, tags: ['archive'] }
    - { role: udisks, tags: ['udisks'] }
    - { role: browsers, tags: ['browsers'] }
    - { role: cups, tags: ['cups'] }
    - { role: office, tags: ['office'] }
    - { role: sound, tags: ['sound'] }
    - { role: mirrorlist, tags: ['mirrorlist'], when: "mirrorlist is defined" }
  vars_prompt:
    - name: user_password
      prompt: "Enter desired user password"
