---
- name: Install Xorg
  pacman: 
    name: xorg-server 
    state: present

- name: Install Xinit
  pacman: 
    name: xorg-xinit 
    state: present

- name: Install xmodmap
  pacman: 
    name: xorg-xmodmap 
    state: present

- name: Install xev
  pacman: 
    name: xorg-xev 
    state: present

- name: Install video driver(s)
  pacman:
    name: "{{ video_drivers }}"
    state: present
