---
- name: Install systemd-resolved
  pacman:
    name: systemd-resovled
    state: present
  tags: "resolve"

- name: Create systemd-resolved config
  template:
    src: "resolved.conf.j2"
    dest: "/etc/systemd/resolved.conf"
    mode: 0644
  notify: Restart systemd-resolved
  