---
- name: Install Firefox
  pacman: name=firefox state=present
  tags:
    - firefox

- name: Install Chromium
  pacman: name=chromium state=present
  tags:
    - chromium

- name: Push rofi browser chooser
  template: src=browser.sh.j2 dest=/usr/local/bin/browser mode=0755
  tags:
    - rofi
    - chooser

- name: Create local desktop application dir
  file: path=/usr/local/share/applications state=directory
  tags:
    - rofi
    - chooser

- name: Push rofi browser chooser desktop file
  copy: src=browser.desktop dest=/usr/local/share/applications/browser.desktop
  tags:
    - rofi
    - chooser

- name: Verify mimeapps.list exists
  file: path=/etc/xdg/mimeapps.list state=touch
  tags:
    - rofi
    - chooser

- name: Set rofi browser chooser as default application for relevant mimetypes
  lineinfile:
    dest: /etc/xdg/mimeapps.list
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^text/html=', line: 'text/html=browser.desktop' }
    - { regexp: '^text/xml=', line: 'text/xml=browser.desktop' }
    - { regexp: '^text/mml=', line: 'text/mml=browser.desktop' }
    - { regexp: '^application/xhtml\+xml=', line: 'application/xhtml+xml=browser.desktop' }
    - { regexp: '^application/xml=', line: 'application/xml=browser.desktop' }
    - { regexp: '^x-scheme-handler/http=', line: 'x-scheme-handler/http=browser.desktop' }
    - { regexp: '^x-scheme-handler/https=', line: 'x-scheme-handler/https=browser.desktop' }
  tags:
    - rofi
    - chooser