---
- name: Install alsa-utils
  pacman: 
    name: alsa-utils 
    state: present

- name: Install PulseAudio
  pacman:
    name:
      - pulseaudio
      - pulseaudio-alsa
      - pavucontrol
    state: present

- name: Install pasystray
  pacman: 
    name: pasystray 
    state: present
